### ISSUE TITLE
Generating Service: No function expression found after module.exports

### ISSUE THREAD

**Issue by periabyte** [feathersjs/generator-feathers#146]
I'm having an error generating a service, but I'm able to generate middlewares
I'm on windows

![image](https://cloud.githubusercontent.com/assets/9923623/18031595/a56fb2b0-6d19-11e6-8f09-ef8278921ef9.png)

```
? What do you want to call your service? sample
? What type of service do you need? generic
? Does your service require users to be authenticated? Yes
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: No function expression found after module.exports
    at Object.exports.addLastInFunction (C:\Users\jeanp\AppData\Roaming\npm\node_modules\feathers-cli\node_modules\generator-feathers\lib\transform.js:81:11)
    at importService (C:\Users\jeanp\AppData\Roaming\npm\node_modules\feathers-cli\node_modules\generator-feathers\generators\service\index.js:16:15)
    at module.exports.generators.Base.extend.writing (C:\Users\jeanp\AppData\Roaming\npm\node_modules\feathers-cli\node_modules\generator-feathers\generators\service\index.js:171:5)
    at Object.<anonymous> (C:\Users\jeanp\AppData\Roaming\npm\node_modules\feathers-cli\node_modules\yeoman-generator\lib\base.js:431:23)
    at C:\Users\jeanp\AppData\Roaming\npm\node_modules\feathers-cli\node_modules\run-async\index.js:26:25
    at new Promise (C:\Users\jeanp\AppData\Roaming\npm\node_modules\feathers-cli\node_modules\core-js\modules\es6.promise.js:191:7)
    at C:\Users\jeanp\AppData\Roaming\npm\node_modules\feathers-cli\node_modules\run-async\index.js:25:19
    at C:\Users\jeanp\AppData\Roaming\npm\node_modules\feathers-cli\node_modules\yeoman-generator\lib\base.js:432:9
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
```

**Comment by daffl** [comment]
This looks like something in the code transformation broke. How does your `services/index.js` look like?

**Comment by periabyte** [comment]
I found the problem thanks to you @daffl, I was trying to use `export default` instead of `module.exports` in my `services/index.js`. Thanks :+1:
