### ISSUE TITLE
npm install feathers-cli@pre -g / feathers generate service  Unhandled 'error' event

### ISSUE THREAD

**Issue by tsora** [feathersjs/generator-feathers#165]
**When you generate a Sequelize service, the path registered value is throwing errors:**

? What kind of service is it? Sequelize
? What is the name of the service? test
? Which path should the service be registered on? /test
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at ServiceGenerator.Base.destinationPath (/usr/local/lib/node_modules/feathers-cli/node_modules/yeoman-generator/lib/index.js:637:28)
    at ServiceGenerator.writing (/usr/local/lib/node_modules/feathers-cli/node_modules/generator-feathers/generators/service/index.js:138:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/feathers-cli/node_modules/yeoman-generator/lib/index.js:408:23)
    at /usr/local/lib/node_modules/feathers-cli/node_modules/run-async/index.js:25:25
    at /usr/local/lib/node_modules/feathers-cli/node_modules/run-async/index.js:24:19
    at /usr/local/lib/node_modules/feathers-cli/node_modules/yeoman-generator/lib/index.js:409:9
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)

**Comment by marshallswain** [comment]
This error occurs when you try to generate a service without having first generated an app.

**Comment by tsora** [comment]
Yes I was attempting it on a previously generated app. That makes sense.

**Comment by daffl** [comment]
Let's keep this open to add a decent error message for this.
