### ISSUE TITLE
Unexpected token on app generate

### ISSUE THREAD

**Issue by gagichce** [feathersjs/generator-feathers#199]
After a successful install of the cli tools, `feathers generate app` results in 
```
/usr/local/lib/node_modules/feathers-cli/node_modules/generator-feathers/lib/generator.js:37
  _packagerInstall(... args) {
                   ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/feathers-cli/node_modules/generator-feathers/generators/app/index.js:3:19)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

Run on MAC OSX 10.11.6, iTerm2 Build 3.0.15

**Comment by marshallswain** [comment]
What version of Node are you using?

**Comment by daffl** [comment]
Although Feathers works with Node 4+ (and most of it also still with 0.10 and 0.12) the generator and CLI and the generated code requires Node v6 or later. The easiest way to install a new Node version is by using [nvm](https://github.com/creationix/nvm). I think we can add a version check to the CLI before it runs anything.

**Comment by gagichce** [comment]
I was using v4.2.1, updated to 6+ and issue resolved
