### ISSUE TITLE
Hook generator fails if generating for a specific service

### ISSUE THREAD

**Issue by tprobinson** [feathersjs/generator-feathers#205]
Hello,

Using `feathers@2.1.1`, `feathers-cli@2.0.3`, `generator-feathers@1.0.4`, `generator-feathers-plugin@0.10.0`, I'm getting the following error when trying to generate a hook for only one service:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: No hook declaration object for 'before' hooks found.
    at Collection.insertHook (/home/trevor/.config/yarn/global/node_modules/generator-feathers/lib/transform.js:35:13)
    at methods.forEach.method (/home/trevor/.config/yarn/global/node_modules/generator-feathers/generators/hook/index.js:32:11)
    at Array.forEach (native)
    at HookGenerator._transformHookFile (/home/trevor/.config/yarn/global/node_modules/generator-feathers/generators/hook/index.js:31:13)
    at HookGenerator._addToService (/home/trevor/.config/yarn/global/node_modules/generator-feathers/generators/hook/index.js:51:30)
    at props.services.forEach.serviceName (/home/trevor/.config/yarn/global/node_modules/generator-feathers/generators/hook/index.js:144:14)
    at Array.forEach (native)
    at HookGenerator.writing (/home/trevor/.config/yarn/global/node_modules/generator-feathers/generators/hook/index.js:143:27)
    at Object.<anonymous> (/home/trevor/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:417:23)
    at /home/trevor/.config/yarn/global/node_modules/run-async/index.js:25:25
```

To reproduce, you can do the following:
```shell
feathers generate app
#  defaults
feathers generate service
#  name doesn't matter, defaults
feathers generate hook
#  name doesn't matter
#  choose any kind option
#  choose the service you made
#  choose any method option
```
Choosing "I will add it" for the kind or methood options does work.

If there's any more information I can provide, let me know.

**Comment by daffl** [comment]
Thank you for reporting! Turns out this was an untested issue from #207. It has been fixed and released in `feathers-cli` v2.0.4
