### ISSUE TITLE
Error when server first run ( npm start )

### ISSUE THREAD

**Issue by SebaBoler** [feathersjs/generator-feathers#262]
I created feathers-chat using command from https://docs.feathersjs.com/guides/chat/service.html
or second https://github.com/feathersjs/generator-feathers. Result is the same.

`Pro-Sebastian:feathers-chat sebastianpietrzak$ npm start

> feathers-chat@0.0.0 start /Users/sebastianpietrzak/Programming/Feathers/feathers-chat
> node src/

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3030
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at Server.setupListenHandle [as _listen2] (net.js:1322:14)
    at listenInCluster (net.js:1370:12)
    at Server.listen (net.js:1466:7)
    at Function.listen (/Users/sebastianpietrzak/Programming/Feathers/feathers-chat/node_modules/express/lib/application.js:618:24)
    at Function.listen (/Users/sebastianpietrzak/Programming/Feathers/feathers-chat/node_modules/feathers/lib/application.js:143:30)
    at Function.listen (/Users/sebastianpietrzak/Programming/Feathers/feathers-chat/node_modules/uberproto/lib/proto.js:30:17)
    at Object.<anonymous> (/Users/sebastianpietrzak/Programming/Feathers/feathers-chat/src/index.js:5:20)
    at Module._compile (module.js:573:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! feathers-chat@0.0.0 start: `node src/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the feathers-chat@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sebastianpietrzak/.npm/_logs/2017-08-22T14_41_39_199Z-debug.log`

i checked issue https://github.com/feathersjs/generator-feathers/issues/78  but i have latest version npm (5.3.0) and node (8.4.0) . I tried uninstall and install again, but result this same.

**Comment by SebaBoler** [comment]
i just kill -9 node  and works. Port was in usage
