### ISSUE TITLE
Service generation results in "Parameter "url" must be a string, not object" when using custom 'connection' parameter

### ISSUE THREAD

**Issue by alzab** [feathersjs/generator-feathers#274]
## Steps to reproduce
1) Install latest feathers-cli (2.3.5)
2) `feathers generate app` - use defaults
3) `feathers generate service` - use defaults + knex + postgresql
4) Open config/default.json and replace the default connection string with an object for the individual parameters (this is perfectly valid for a knex connection). In my case it was:
```
"connection": {
  "host": "PGHOST",
  "port": "PGPORT",
  "user": "PGUSER",
  "password": "PGPASSWORD",
  "database": "PGDATABASE"
}
```
5) `feathers generate service` - use defaults + knex + postgresql (again, only with a different service name of course). This time the following error results:
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

TypeError: Parameter "url" must be a string, not object
    at Url.parse (url.js:102:11)
    at Object.urlParse [as parse] (url.js:96:5)
    at ConnectionGenerator._getConfiguration (/home/alex/.nvm/versions/node/v8.2.1/lib/node_modules/feathers-cli/node_modules/generator-feathers/generators/connection/index.js:46:24)
    at ConnectionGenerator._writeConfiguration (/home/alex/.nvm/versions/node/v8.2.1/lib/node_modules/feathers-cli/node_modules/generator-feathers/generators/connection/index.js:103:32)
    at ConnectionGenerator.writing (/home/alex/.nvm/versions/node/v8.2.1/lib/node_modules/feathers-cli/node_modules/generator-feathers/generators/connection/index.js:301:10)
    at Object.<anonymous> (/home/alex/.nvm/versions/node/v8.2.1/lib/node_modules/feathers-cli/node_modules/yeoman-generator/lib/index.js:417:23)
    at /home/alex/.nvm/versions/node/v8.2.1/lib/node_modules/feathers-cli/node_modules/run-async/index.js:25:25
    at Promise (<anonymous>)
    at /home/alex/.nvm/versions/node/v8.2.1/lib/node_modules/feathers-cli/node_modules/run-async/index.js:24:19
    at /home/alex/.nvm/versions/node/v8.2.1/lib/node_modules/feathers-cli/node_modules/yeoman-generator/lib/index.js:418:9
```
It's clearly being triggered by using the custom connection object - I assume, however, that it should be able to handle this?

**Comment by daffl** [comment]
I think this should be fixed via #273 as well, can you confirm with `feathers-cli@2.3.6`?

**Comment by alzab** [comment]
Can confirm, looks like it's now solved! Thanks for the fix!

**Comment by daffl** [comment]
Sweet. Thanks for double checking.
