### ISSUE TITLE
Generate custom service

### ISSUE THREAD

**Issue by sylvainlap** [feathersjs/generator-feathers#304]
When I try to generate a custom service, I got his error.

```
$ npx @feathersjs/cli g service
npx: 1 installé(s) en 1.645s
Path must be a string. Received undefined
C:\Users\sylva\AppData\Roaming\npm-cache\_npx\7268\node_modules\@feathersjs\cli\bin\feathers.js
? What kind of service is it? A custom service
? What is the name of the service? foobar
? Which path should the service be registered on? /foobar
? Does the service require authentication? Yes
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: src//services/index.js seems to have more than one function declaration and we can not register the new service. Did you modify it?
    at ServiceGenerator._transformCode (C:\Users\sylva\AppData\Roaming\npm-cache\_npx\7268\node_modules\@feathersjs\cli\node_modules\generator-feathers\generators\service\index.js:106:13)
    at ServiceGenerator.writing (C:\Users\sylva\AppData\Roaming\npm-cache\_npx\7268\node_modules\@feathersjs\cli\node_modules\generator-feathers\generators\service\index.js:146:32)
    at Object.<anonymous> (C:\Users\sylva\AppData\Roaming\npm-cache\_npx\7268\node_modules\@feathersjs\cli\node_modules\yeoman-generator\lib\index.js:399:25)
    at C:\Users\sylva\AppData\Roaming\npm-cache\_npx\7268\node_modules\@feathersjs\cli\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Users\sylva\AppData\Roaming\npm-cache\_npx\7268\node_modules\@feathersjs\cli\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Users\sylva\AppData\Roaming\npm-cache\_npx\7268\node_modules\@feathersjs\cli\node_modules\yeoman-generator\lib\index.js:400:11)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by daffl** [comment]
How does your `services/index.js` look like?

**Comment by sylvainlap** [comment]
Here is my `services/index.js`:

```
const answers = require('./answers/answers.service.js');
const companies = require('./companies/companies.service.js');
const messages = require('./messages/messages.service.js');
const questions = require('./questions/questions.service.js');
const segmentTypes = require('./segment_types/segment_types.service.js');
const segments = require('./segments/segments.service.js');
const slackbots = require('./slackbots/slackbots.service.js');
const surveys = require('./surveys/surveys.service.js');
const threads = require('./threads/threads.service.js');
const users = require('./users/users.service.js');

module.exports = (app) => {
  app.configure(answers);
  app.configure(companies);
  app.configure(questions);
  app.configure(segmentTypes);
  app.configure(segments);
  app.configure(slackbots);
  app.configure(surveys);
  app.configure(users);
  app.configure(threads);
  app.configure(messages);
};
```

**Comment by daffl** [comment]
Well, as the error message says, that file should not be modified manually since the codemods will not work then. It has to be

```
module.exports = function(app) {
  app.configure(answers);
  app.configure(companies);
  app.configure(questions);
  app.configure(segmentTypes);
  app.configure(segments);
  app.configure(slackbots);
  app.configure(surveys);
  app.configure(users);
  app.configure(threads);
  app.configure(messages);
};
```

Since it is looking for a `function` declaration.

**Comment by sylvainlap** [comment]
OK I understand. Thanks !
