### ISSUE TITLE
Error: Invalid 'secret' provider configuration.

### ISSUE THREAD

**Issue by gardner** [feathersjs/generator-feathers#36]
**Steps to reproduce**

    npm install -g yo
    npm install -g generator-feathers
    mkdir f
    cd f
    yo feathers:app

<img width="639" alt="screen shot 2016-02-16 at 1 18 17 pm" src="https://cloud.githubusercontent.com/assets/787026/13063747/ebc056e6-d4af-11e5-932b-2dde9fef11f9.png">

    npm install
    npm start

**Observed Behavior**

    > trv@0.0.0 start /Users/gardner/src/f
    > node src/

    /Users/gardner/src/f/node_modules/feathers-authentication/lib/index.js:81
                throw new Error('Invalid \'' + key + '\' provider configuration.\nYou need to provide your \'clientID\' and \'clientSecret\' if using an OAuth2 provider or your \'consumerKey\' and \'consumerSecret\' if using an OAuth1 provider.');
                ^

    Error: Invalid 'secret' provider configuration.
    You need to provide your 'clientID' and 'clientSecret' if using an OAuth2 provider or your 'consumerKey' and 'consumerSecret' if using an OAuth1 provider.
        at /Users/gardner/src/f/node_modules/feathers-authentication/lib/index.js:81:19
        at Array.forEach (native)
        at EventEmitter.<anonymous> (/Users/gardner/src/f/node_modules/feathers-authentication/lib/index.js:66:28)
        at EventEmitter.configure (/Users/gardner/src/f/node_modules/feathers/lib/application.js:137:8)
        at Object.<anonymous> (app.js:29:4)
        at Module._compile (module.js:413:34)
        at loader (/Users/gardner/src/f/node_modules/babel-register/lib/node.js:128:5)
        at Object.require.extensions.(anonymous function) [as .js] (/Users/gardner/src/f/node_modules/babel-register/lib/node.js:138:7)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)
        at Module.require (module.js:367:17)
        at require (internal/module.js:16:19)
        at Object.<anonymous> (/Users/gardner/src/f/src/index.js:3:11)
        at Module._compile (module.js:413:34)
        at Object.Module._extensions..js (module.js:422:10)
        at Module.load (module.js:357:32)

    npm ERR! Darwin 15.3.0
    npm ERR! argv "/Users/gardner/.nvm/versions/node/v5.5.0/bin/node" "/Users/gardner/.nvm/versions/node/v5.5.0/bin/npm" "start"
    npm ERR! node v5.5.0
    npm ERR! npm  v3.3.12
    npm ERR! code ELIFECYCLE
    npm ERR! trv@0.0.0 start: `node src/`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the trv@0.0.0 start script 'node src/'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the trv package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node src/
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls trv
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/gardner/src/f/npm-debug.log

**Expected Behavior**
Default configuration to run or display informational message about what needs to be done.

**Comment by gardner** [comment]
Thank you to @ekryski

**Comment by ekryski** [comment]
@gardner no problem. Thanks for reporting. I knew about it but it gave me a kick in the ass to fix it faster!
