### ISSUE TITLE
tengo este error pueden ayudarme

### ISSUE THREAD

**Issue by Vistor2012** [feathersjs/generator-feathers#373]
module.js:328
    throw err;
    ^

Error: Cannot find module 'mongoose'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/victor/seminario/proyecto2018/database/connect.js:1:80)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

**Comment by daffl** [comment]
Run `npm i mongoose --save` or `npm install` if it is already in your `package.json` `dependencies`.
