### ISSUE TITLE
Windows - Trying to copy from a source that does not exist

### ISSUE THREAD

**Issue by ChronSyn** [feathersjs/generator-feathers#384]
**What happened?**
An error was experienced while trying to generate a feathers app

**How did it happen?**
After following the instructions in the readme, running `yo feathers` and following the prompts, the error occurs after completing "What type of API are you making?" (with REST, and REST + Realtime via Socket.io options).

**System setup**
OS: Windows 10 x64
Packager: NPM
Node version: 10.0.0 (also tried 7.2.1)

Administrative level access is being used, and the folder mentioned in the error exists. The issue also happens with the feathersjs-cli (presumably because it's based on this).

**Error**
```
AssertionError: Trying to copy from a source that does not exist: C:\Program Files (x86)\Nodist\bin\node_modules\generator-feathers\generators\app\templates\static
    at EditionInterface.exports.copy (C:\Program Files (x86)\Nodist\bin\node_modules\generator-feathers\node_modules\mem-fs-editor\lib\actions\copy.js:48:3)
    at AppGenerator.writing (C:\Program Files (x86)\Nodist\bin\node_modules\generator-feathers\generators\app\index.js:127:13)
    at Object.<anonymous> (C:\Program Files (x86)\Nodist\bin\node_modules\generator-feathers\node_modules\yeoman-generator\lib\index.js:424:27)
    at C:\Program Files (x86)\Nodist\bin\node_modules\generator-feathers\node_modules\run-async\index.js:25:25
    at C:\Program Files (x86)\Nodist\bin\node_modules\generator-feathers\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Program Files (x86)\Nodist\bin\node_modules\generator-feathers\node_modules\yeoman-generator\lib\index.js:425:13)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

**Comment by ChronSyn** [comment]
Apparently this is an issue with nodist, and not feathers. Closing.

**Comment by daintym0sh** [comment]
@ChronSyn Were you able to figure this one out? I am getting the same error and can't seem to find anything on how it's related to nodist.

**Comment by ChronSyn** [comment]
> @ChronSyn Were you able to figure this one out? I am getting the same error and can't seem to find anything on how it's related to nodist.

I've not used Feathers since 2018 so I don't recall if I ever solved the issue.
