### ISSUE TITLE
feathers-plus generate app crashing

### ISSUE THREAD

**Issue by AnthoniG** [feathersjs/generator-feathers#394]
I am getting an error what I try and do an install of the app.
node version : 10/13.0
npm version: 6.4.1
linux mint version : Linux Mint 18.3 (Sylvia)

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'test:all' of undefined
    at app (/home/anthoni/.nvm/versions/node/v10.13.0/lib/node_modules/@feathers-plus/cli/node_modules/@feathers-plus/generator-feathers-plus/generators/writing/index.js:341:42)
    at generatorWriting (/home/anthoni/.nvm/versions/node/v10.13.0/lib/node_modules/@feathers-plus/cli/node_modules/@feathers-plus/generator-feathers-plus/generators/writing/index.js:266:7)
    at AppGenerator.writing (/home/anthoni/.nvm/versions/node/v10.13.0/lib/node_modules/@feathers-plus/cli/node_modules/@feathers-plus/generator-feathers-plus/generators/app/index.js:187:5)
    at Object.<anonymous> (/home/anthoni/.nvm/versions/node/v10.13.0/lib/node_modules/@feathers-plus/cli/node_modules/yeoman-generator/lib/index.js:424:27)
    at /home/anthoni/.nvm/versions/node/v10.13.0/lib/node_modules/@feathers-plus/cli/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /home/anthoni/.nvm/versions/node/v10.13.0/lib/node_modules/@feathers-plus/cli/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/home/anthoni/.nvm/versions/node/v10.13.0/lib/node_modules/@feathers-plus/cli/node_modules/yeoman-generator/lib/index.js:425:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at Immediate.setImmediate (/home/anthoni/.nvm/versions/node/v10.13.0/lib/node_modules/@feathers-plus/cli/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by daffl** [comment]
Please report this in https://github.com/feathers-plus/generator-feathers-plus

**Comment by eddyystop** [comment]
See reply in https://github.com/feathers-plus/generator-feathers-plus/issues/121
