### ISSUE TITLE
Failed to a generate hook

### ISSUE THREAD

**Issue by anton-yarchuk** [feathersjs/generator-feathers#472]
After some time CLI started to refuse to generate hooks:
  ```
feathers generate hook
events.js:173
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'files' of undefined
    at subloop (/home/user/.nvm/versions/node/v11.10.0/lib/node_modules/@feathersjs/cli/node_modules/generator-feathers/node_modules/node-dir/lib/paths.js:92:58)
    at /home/user/.nvm/versions/node/v11.10.0/lib/node_modules/@feathersjs/cli/node_modules/generator-feathers/node_modules/node-dir/lib/paths.js:107:13
    at onDirRead (/home/user/.nvm/versions/node/v11.10.0/lib/node_modules/@feathersjs/cli/node_modules/generator-feathers/node_modules/node-dir/lib/paths.js:139:35)
    at onStat (/home/user/.nvm/versions/node/v11.10.0/lib/node_modules/@feathersjs/cli/node_modules/generator-feathers/node_modules/node-dir/lib/paths.js:154:14)
    at Object.files (/home/user/.nvm/versions/node/v11.10.0/lib/node_modules/@feathersjs/cli/node_modules/generator-feathers/node_modules/node-dir/lib/paths.js:162:12)
    at HookGenerator._listServices (/home/user/.nvm/versions/node/v11.10.0/lib/node_modules/@feathersjs/cli/node_modules/generator-feathers/generators/hook/index.js:12:23)
    at HookGenerator.prompting (/home/user/.nvm/versions/node/v11.10.0/lib/node_modules/@feathersjs/cli/node_modules/generator-feathers/generators/hook/index.js:95:27)
    at Object.<anonymous> (/home/user/.nvm/versions/node/v11.10.0/lib/node_modules/@feathersjs/cli/node_modules/yeoman-generator/lib/index.js:427:27)
    at /home/user/.nvm/versions/node/v11.10.0/lib/node_modules/@feathersjs/cli/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /home/user/.nvm/versions/node/v11.10.0/lib/node_modules/@feathersjs/cli/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/home/user/.nvm/versions/node/v11.10.0/lib/node_modules/@feathersjs/cli/node_modules/yeoman-generator/lib/index.js:428:13)
    at processImmediate (timers.js:637:19)
Emitted 'error' event at:
    at Immediate.setImmediate (/home/user/.nvm/versions/node/v11.10.0/lib/node_modules/@feathersjs/cli/node_modules/yeoman-generator/lib/index.js:436:22)
    at processImmediate (timers.js:637:19)
```

Node 11.10.0 installed using nvm.
Linux Mint 19.1

2 strange things:
- I still can generate apps and services, but not hooks
- I made a git checkout to some previous state of the project, but the error did not disappear.

CLI is installed globally. I've reinstalled it - didn't help.

Also, I have checked files permission - all good.

**Comment by anton-yarchuk** [comment]
Please nevermind, the problem disappeared after reboot.
