### ISSUE TITLE
New Generated feathersjs app failed when start

### ISSUE THREAD

**Issue by spiritkiddie** [feathersjs/generator-feathers#607]
I have tried switch between nodejs versions from version 12 upwards and still have this error.
I'm new to feathers js, i dont understand the error and dont know where to fix it. Please any help

info: Feathers application started on http://localhost:3030
internal/crypto/keys.js:299
      throw new ERR_INVALID_ARG_TYPE(
      ^
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be one of type Buffer, TypedArray, DataView, string, or KeyObject. Received type object
    at prepareSecretKey (internal/crypto/keys.js:299:13)
    at new Hmac (internal/crypto/hash.js:101:9)
    at Object.createHmac (crypto.js:139:10)
    at createHMAC (C:\**\**\Desktop\DreamFox\node_modules\pg\lib\sasl.js:133:17)
    at Hi (C:\**\**\Desktop\DreamFox\node_modules\pg\lib\sasl.js:137:13)
    at Object.continueSession (C:\**\**\Desktop\DreamFox\node_modules\pg\lib\sasl.js:32:24)
    at Client._handleAuthSASLContinue (C:\**\**\Desktop\DreamFox\node_modules\pg\lib\client.js:257:10)
    at Connection.emit (events.js:210:5)
    at C:\**\**\Desktop\DreamFox\node_modules\pg\lib\connection.js:115:12
    at Parser.parse (C:\***\***\Desktop\DreamFox\node_modules\pg-protocol\dist\parser.js:40:17) {
  code: 'ERR_INVALID_ARG_TYPE'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dream-fox@0.0.0 start: `node server/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dream-fox@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\**\**\***\**\npm-cache\_logs\2021-02-04T16_32_52_210Z-debug.log

**Comment by J3m5** [comment]
Try to update and reinstall your node modules.

**Comment by spiritkiddie** [comment]
i just deleted node_modules folder and npm install the whole package, still the error persist.

**Comment by daffl** [comment]
This is probably related to https://github.com/brianc/node-postgres/issues/2371 and most likely a configuration problem with your database. Make sure the database has been created and you set the correct password in the connection [string.](url)

**Comment by spiritkiddie** [comment]
Thanks for the help! this been my first time getting my hands on feathersjs,  i missed passing user:password to the connection string. Finally the app is up and running now.
