### ISSUE TITLE
Error on generating restrict-to-sender hook

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/generator-feathers#71]
I got the following error while generating the restrict-to-sender hook in the guide:

```
Bitovis-MacBook-Pro:feathers-canjs-starter Bitovi$ yo feathers:hook
? What do you want to call your hook? restrict-to-sender
? What type of hook do you need? before hook
? What service is this hook for? messages
? What method is this hook for? update, patch, remove
events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'loc' of null
    at print (/Users/Bitovi/.npm-packages/lib/node_modules/generator-feathers/node_modules/recast/lib/printer.js:72:37)
    at exports.printComments (/Users/Bitovi/.npm-packages/lib/node_modules/generator-feathers/node_modules/recast/lib/comments.js:324:22)
    at printWithComments (/Users/Bitovi/.npm-packages/lib/node_modules/generator-feathers/node_modules/recast/lib/printer.js:61:16)
    at print (/Users/Bitovi/.npm-packages/lib/node_modules/generator-feathers/node_modules/recast/lib/printer.js:66:20)
    at Printer.print (/Users/Bitovi/.npm-packages/lib/node_modules/generator-feathers/node_modules/recast/lib/printer.js:118:21)
    at Object.print (/Users/Bitovi/.npm-packages/lib/node_modules/generator-feathers/node_modules/recast/main.js:6:33)
    at traverse.pre (/Users/Bitovi/.npm-packages/lib/node_modules/generator-feathers/lib/transform.js:32:25)
    at visit (/Users/Bitovi/.npm-packages/lib/node_modules/generator-feathers/node_modules/ast-traverse/ast-traverse.js:16:19)
    at visit (/Users/Bitovi/.npm-packages/lib/node_modules/generator-feathers/node_modules/ast-traverse/ast-traverse.js:29:25)
    at visit (/Users/Bitovi/.npm-packages/lib/node_modules/generator-feathers/node_modules/ast-traverse/ast-traverse.js:29:25)
```

**Comment by marshallswain** [comment]
If you revert the changes done to the messages/hooks/index.js file in the [serializing messages section of the guide](http://docs.feathersjs.com/getting-started/formatting-and-hooks.html#serializing-messages,) it will work.

**Comment by daffl** [comment]
I knew we could count on your dilligence :) This should be fixed now via https://github.com/feathersjs/feathers-docs/commit/94333aed64263c0a2cecfca2c53bf7f03c5204b9.
