### ISSUE TITLE
All generator tests fail on node v5.8.0

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/generator-feathers#98]
The generator-feathers tests fail, but the transforms all pass.
```
generator-feathers - all fail
    1) feathers:app
    2) feathers:service(memory)
    3) feathers:service(generic)
    4) feathers:hook

  transforms - all pass
    ✓ simple addImport
    ✓ addImport with 'use strict';
    ✓ findFirstNodeAfter
    ✓ addLastInFunction
    ✓ addToArrayInObject
    ✓ addToArrayInObject for hook objects


  6 passing (35s)
  4 failing

  1) generator-feathers feathers:app:

      Uncaught AssertionError: Got correct exit status
      + expected - actual

      -1
      +0
      
      at ChildProcess.<anonymous> (generators.test.js:21:14)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

  2) generator-feathers feathers:service(memory):

      Uncaught AssertionError: Got correct exit status
      + expected - actual

      -1
      +0
      
      at ChildProcess.<anonymous> (generators.test.js:21:14)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

  3) generator-feathers feathers:service(generic):

      Uncaught AssertionError: Got correct exit status
      + expected - actual

      -1
      +0
      
      at ChildProcess.<anonymous> (generators.test.js:21:14)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

  4) generator-feathers feathers:hook:

      Uncaught AssertionError: Got correct exit status
      + expected - actual

      -1
      +0
      
      at ChildProcess.<anonymous> (generators.test.js:21:14)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

```

**Comment by daffl** [comment]
The tests are passing for me and on Travis CI in 5.8.0 (see https://travis-ci.org/feathersjs/generator-feathers/jobs/118769631#L128). Could it be a local setup problem? We may want to add the error output in https://github.com/feathersjs/generator-feathers/blob/master/test/generators.test.js#L20 to make debugging easier.

**Comment by marshallswain** [comment]
If I do `console.log(arguments)` there, I don't get very helpful output:
```
{ '0': 1, '1': null }
    1) feathers:app
{ '0': 1, '1': null }
    2) feathers:service(memory)
{ '0': 1, '1': null }
    3) feathers:service(generic)
{ '0': 1, '1': null }
    4) feathers:hook
```

@daffl can you check my global modules against yours with `npm -g ls --depth=0`?
```
Bitovis-MacBook-Pro:generator-feathers Bitovi$ npm -g ls --depth=0
/Users/Bitovi/.nvm/versions/node/v5.8.0/lib
├── donejs@0.8.0
├── feathers-cli@1.1.1
├── generator-feathers@0.6.20
├── generator-feathers-plugin@0.6.9
├── grunt-cli@1.1.0
├── http-server@0.9.0
├── npm@3.8.3
├── steal-tools@0.15.5
└── yo@1.7.0
```

**Comment by marshallswain** [comment]
My environment was still messed up from before I installed using nvm.  I created a new user in OS X  and it works fine.
